add_library(logicscope_lib src/simulator.cpp)
target_include_directories(logicscope_lib PUBLIC include)
target_link_libraries(logicscope_lib PUBLIC project_options)
add_executable(logicscope src/main.cpp)
target_link_libraries(logicscope PRIVATE logicscope_lib)
if(BUILD_TESTING)
  add_executable(logicscope_tests tests/tests.cpp)
  target_link_libraries(logicscope_tests PRIVATE logicscope_lib)
  add_test(NAME logicscope_unit COMMAND logicscope_tests)
endif()
